### ISSUE TITLE
Investigate invoice creation on update vs. create order

### ISSUE THREAD

**Issue by JustinSainton** [zao-web/zao-woocommerce-quickbooks-online-integration#11]
See https://zaoweb.slack.com/archives/C5MEB4HMY/p1506975215000302

We've had scenarios where the QB Invoice is created only on update, not on create. Need to understand why this is, as it can create a non-optimal experience, especially when splitting orders.

**Comment by JustinSainton** [comment]
I _think_ we have this fixed as of 7f557debc516cc64286211897a0dd91acc36e4fe.

**Comment by JustinSainton** [comment]
@jtsternberg Will want your eyes on that commit though.

**Comment by jtsternberg** [comment]
That commit looks good, but the creation issue was resolved through #12.
