### ISSUE TITLE
On save, Quickbooks returns an internal error on invoice creation

### ISSUE THREAD

**Issue by JustinSainton** [zao-web/zao-woocommerce-quickbooks-online-integration#12]
It still creates the invoice, but the internal error is mystifying.  Read a few online forums indicating it could be a type mismatch (passing strings for Qty and Amount vs. Float) - but strongly typing those didn't resolve the issue.

**Comment by jtsternberg** [comment]
What is the error?

**Comment by JustinSainton** [comment]
There was an error creating a QuickBooks Invoice for this order: 226364
The Status code is: 400 
The Helper message is: Invalid auth/bad request (got a 400, expected HTTP/1.1 20X or a redirect) 
The Response message is: A business validation error has occurred while processing your requestBusiness Validation Error: Unexpected Internal Error. (-30003) 
The Intuit Error Type is: ValidationFault 
The Intuit Error Code is: 6000 
The Intuit Error Message is: A business validation error has occurred while processing your request 
The Intuit Error Detail is: Business Validation Error: Unexpected Internal Error. (-30003)

**Comment by jtsternberg** [comment]
It's because when you click the ajax save button by the line items, and the order has not yet been _created_, there is no associated customer, which makes the `CustomerRef` QB param empty, which triggers that error. Should be good now.
