### ISSUE TITLE
Add Backorder status icon

### ISSUE THREAD

**Issue by JustinSainton** [zao-web/zao-woocommerce-quickbooks-online-integration#13]

**Comment by jtsternberg** [comment]
Like, instead of this guy (or in addition to), right?

![](http://b.ustin.co/4nzU6m+)

**Comment by jtsternberg** [comment]
Or this? 

![](http://b.ustin.co/yRgBh7+)

**Comment by jtsternberg** [comment]
(This has been closed via commit to the wholesale plugin: https://github.com/zao-web/zao-woocommerce-wholesale/commit/ccef1aaeceea822533c3df7d50b4ff62007c4c78)
