### ISSUE TITLE
Use data stores where relevant

### ISSUE THREAD

**Issue by JustinSainton** [zao-web/zao-woocommerce-quickbooks-online-integration#5]
Currently, we have a fair bit of baked in assumptions about orders being posts. This has traditionally been the case, but with custom data stores, we can no longer bank on this.  

We should be using the meta helpers on the order object instead of *_post_meta when getting order data.

**Comment by jtsternberg** [comment]
More updates needed, for places like these: https://github.com/zao-web/zao-woocommerce-quickbooks-online-integration/blob/b1104a34aca0dfeabedd453cd705b36da06d970d/includes/classes/admin/connected-object-base.php#L80
