### ISSUE TITLE
When importing Quickbooks Customers from Quickbooks, import all data

### ISSUE THREAD

**Issue by JustinSainton** [zao-web/zao-woocommerce-quickbooks-online-integration#9]
Specifically, I'm seeing that QB has "Terms" and "Online Payment" options that we do not import to the WP user, and therefore, do not send back to the invoice.

**Comment by jtsternberg** [comment]
I think we're good here. Cannot send payment method to invoice as there is no parameter for it: https://developer.intuit.com/docs/api/accounting/invoice
